version: "3.9"
services:
  soundboard:
    image: benwallacestock/mumble-soundboard
    ports:
      - "5000:5000"
    environment:
      # URL used to connect to the database
      - DATABASE_URL=postgresql://mumble-soundboard-user:<DATABASE_PASSWORD>@db:5432/mumble-soundboard

      # Configure the the Mumble connection settings
      - MUMBLE_BOT_IP=<MUMBLE_IP_ADDRESS>
      - MUMBLE_BOT_PORT=<MUMBLE_PORT_ADDRESS>
      - MUMBLE_BOT_USERNAME=<MUMBLE_USERNAME>

      # Configure limits on using the soundboard
      - MUMBLE_BOT_TIMEOUT_SECONDS=60
      - MAX_SOUND_DURATION=10

      # Default admin password
      - ADMIN_PASSWORD=<ADMIN_PASSWORD>

      # Key used to sign session cookies
      - SECRET_KEY=<SECRET_KEY>
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /path/to/soundbaord/data:/data/

  db:
    image: postgres:12-alpine
    volumes:
      - /path/to/database/data:/var/lib/postgresql/data/
    environment:
      # Setup the postgres database
      - POSTGRES_USER=mumble-soundboard-user
      - POSTGRES_PASSWORD=<DATABASE_PASSWORD>
      - POSTGRES_DB=mumble-soundboard
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5